<a href="https://colab.research.google.com/github/codewithcoderealm/pytorch-ai/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamental

In [8]:
print("Hello I'm execited to learn PyTorch!")

Hello I'm execited to learn PyTorch!


In [9]:
import torch
print(torch.__version__)

2.11.0+cpu


In [10]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction To Tensors

### Creating Tensors

Pytorch Tensors Documentation `torch.Tensor()` = https://docs.pytorch.org/docs/2.12/tensors.html

In [41]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [42]:
scaler.ndim

0

In [43]:
# Get tensor back as Python int
scaler.item()

7

In [44]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [45]:
vector.ndim

1

In [46]:
vector.shape

torch.Size([2])

In [47]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [48]:
MATRIX.ndim

2

In [49]:
MATRIX[0]

tensor([7, 8])

In [50]:
MATRIX.shape

torch.Size([2, 2])

In [51]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [52]:
TENSOR.ndim

3

In [53]:
TENSOR.shape

torch.Size([1, 3, 3])

In [54]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [55]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information tensor

1. Tensors not right datatype - tot do get datatype from a tensor, can user `tensor.dttype`

In [56]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5027, 0.7710, 0.6491, 0.7372],
        [0.6380, 0.0572, 0.0166, 0.8466],
        [0.6304, 0.8039, 0.8457, 0.6865]])

In [57]:
print(some_tensor)

tensor([[0.5027, 0.7710, 0.6491, 0.7372],
        [0.6380, 0.0572, 0.0166, 0.8466],
        [0.6304, 0.8039, 0.8457, 0.6865]])


In [58]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")


Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### manipulating Tensors (tensors operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [59]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [60]:
# Mulitply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [61]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [62]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [63]:
### Matrix Multiplication
print(tensor,"*",tensor)
print(f"Equal : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal : tensor([1, 4, 9])


In [64]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 294 µs, sys: 40 µs, total: 334 µs
Wall time: 293 µs


tensor(14)

In [65]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[1.5131, 1.4456, 1.9860, 2.1747, 2.1973, 1.4497, 2.0220, 2.1636, 1.4998,
         2.4227],
        [1.9824, 2.5068, 3.6159, 3.7994, 2.7150, 2.0024, 3.9943, 3.8609, 2.5109,
         3.1520],
        [1.7585, 1.7714, 2.2992, 2.9316, 2.6997, 1.8061, 2.2242, 3.0670, 2.2753,
         2.8005],
        [2.2147, 2.3462, 3.1607, 3.0593, 2.8034, 1.6679, 3.4007, 3.4391, 2.5509,
         2.8299],
        [1.8108, 2.0235, 2.6646, 3.2489, 3.2367, 1.9882, 2.8495, 3.2163, 2.6190,
         3.3162],
        [1.7718, 1.4489, 2.6978, 3.1085, 2.5931, 1.7360, 3.2136, 2.9369, 2.0796,
         2.8127],
        [1.6215, 1.8106, 2.1518, 2.5555, 2.3426, 1.4660, 2.5454, 2.5904, 1.6091,
         2.6938],
        [2.3048, 1.9669, 3.1246, 3.1091, 3.0270, 1.9544, 3.4530, 3.2758, 2.0966,
         3.3601],
        [1.5890, 1.1821, 2.3838, 2.7821, 2.3649, 1.6445, 3.1115, 2.9204, 1.4075,
         2.8845],
        [1.3969, 1.2628, 2.1788, 2.3260, 2.0763, 1.5506, 2.0534, 2.6989, 1.5987,
         2.4165]])

In [66]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [67]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [68]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [69]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum (tensor aggregation)

In [75]:
x= torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [74]:
torch.max(x),x.min()

(tensor(90), tensor(0))

In [80]:
#Find the mean -  note: the torch.mean( )function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [82]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))