<a href="https://colab.research.google.com/github/codewithcoderealm/pytorch-ai/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamental

In [3]:
print("Hello I'm execited to learn PyTorch!")

Hello I'm execited to learn PyTorch!


In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [6]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction To Tensors

### Creating Tensors

Pytorch Tensors Documentation `torch.Tensor()` = https://docs.pytorch.org/docs/2.12/tensors.html

In [5]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
# Get tensor back as Python int
scaler.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [4]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [5]:
MATRIX.ndim

2

In [6]:
MATRIX[0]

tensor([7, 8])

In [7]:
MATRIX.shape

torch.Size([2, 2])

In [8]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])