<a href="https://colab.research.google.com/github/codewithcoderealm/pytorch-ai/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamental

In [1]:
print("Hello I'm execited to learn PyTorch!")

Hello I'm execited to learn PyTorch!


In [2]:
import torch
print(torch.__version__)

2.11.0+cpu


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction To Tensors

### Creating Tensors

Pytorch Tensors Documentation `torch.Tensor()` = https://docs.pytorch.org/docs/2.12/tensors.html

In [4]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
# Get tensor back as Python int
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information tensor

1. Tensors not right datatype - tot do get datatype from a tensor, can user `tensor.dttype`

In [20]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5592, 0.0791, 0.7932, 0.2962],
        [0.0175, 0.8360, 0.6676, 0.2886],
        [0.2975, 0.4233, 0.6948, 0.4364]])

In [21]:
print(some_tensor)

tensor([[0.5592, 0.0791, 0.7932, 0.2962],
        [0.0175, 0.8360, 0.6676, 0.2886],
        [0.2975, 0.4233, 0.6948, 0.4364]])


In [23]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")


Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### manipulating Tensors (tensors operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [25]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Mulitply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [29]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])