<a href="https://colab.research.google.com/github/codewithcoderealm/pytorch-ai/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamental

In [ ]:
print("Hello I'm execited to learn PyTorch!")

Hello I'm execited to learn PyTorch!


In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction To Tensors

### Creating Tensors

Pytorch Tensors Documentation `torch.Tensor()` = https://docs.pytorch.org/docs/2.12/tensors.html

In [ ]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information tensor

1. Tensors not right datatype - tot do get datatype from a tensor, can user `tensor.dttype`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5027, 0.7710, 0.6491, 0.7372],
        [0.6380, 0.0572, 0.0166, 0.8466],
        [0.6304, 0.8039, 0.8457, 0.6865]])

In [ ]:
print(some_tensor)

tensor([[0.5027, 0.7710, 0.6491, 0.7372],
        [0.6380, 0.0572, 0.0166, 0.8466],
        [0.6304, 0.8039, 0.8457, 0.6865]])


In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")


Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### manipulating Tensors (tensors operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Mulitply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
### Matrix Multiplication
print(tensor,"*",tensor)
print(f"Equal : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal : tensor([1, 4, 9])


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 294 µs, sys: 40 µs, total: 334 µs
Wall time: 293 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[1.5131, 1.4456, 1.9860, 2.1747, 2.1973, 1.4497, 2.0220, 2.1636, 1.4998,
         2.4227],
        [1.9824, 2.5068, 3.6159, 3.7994, 2.7150, 2.0024, 3.9943, 3.8609, 2.5109,
         3.1520],
        [1.7585, 1.7714, 2.2992, 2.9316, 2.6997, 1.8061, 2.2242, 3.0670, 2.2753,
         2.8005],
        [2.2147, 2.3462, 3.1607, 3.0593, 2.8034, 1.6679, 3.4007, 3.4391, 2.5509,
         2.8299],
        [1.8108, 2.0235, 2.6646, 3.2489, 3.2367, 1.9882, 2.8495, 3.2163, 2.6190,
         3.3162],
        [1.7718, 1.4489, 2.6978, 3.1085, 2.5931, 1.7360, 3.2136, 2.9369, 2.0796,
         2.8127],
        [1.6215, 1.8106, 2.1518, 2.5555, 2.3426, 1.4660, 2.5454, 2.5904, 1.6091,
         2.6938],
        [2.3048, 1.9669, 3.1246, 3.1091, 3.0270, 1.9544, 3.4530, 3.2758, 2.0966,
         3.3601],
        [1.5890, 1.1821, 2.3838, 2.7821, 2.3649, 1.6445, 3.1115, 2.9204, 1.4075,
         2.8845],
        [1.3969, 1.2628, 2.1788, 2.3260, 2.0763, 1.5506, 2.0534, 2.6989, 1.5987,
         2.4165]])

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum (tensor aggregation)

In [ ]:
x= torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.max(x),x.min()

(tensor(90), tensor(0))

In [ ]:
#Find the mean -  note: the torch.mean( )function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

NameError: name 'x' is not defined

In [ ]:
# Find  the position in tensor that minimum value with argmin() -> returns index
x.argmin(),x.argmax()

In [ ]:
x[9]

## Reshaping, stacking, sequeezing and unsequeezing tensors

* Reshaping- reshapes an input tensor to defined shape
* stacking - combine multiple tensors
* sequeeze - remove all
* unsequeeze - add a `1` dimension to a target tensor
* permute

In [ ]:
import torch

In [ ]:
x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimnesion
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.seqeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_shaed
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds s single dimension to target tensor at specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - reaarages the dimensions of a target tensor in sepcified order
x_original = torch.rand(size=(224,224,3))
# permute the oriignal tensor to rearrage the axis order
x_permuted = x_original.permute(2,0,1) #shifts axis0_>1,1->2,2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.4982, 0.6323, 0.1069],
         [0.4579, 0.4850, 0.9506],
         [0.4557, 0.8175, 0.7258],
         ...,
         [0.5183, 0.0174, 0.5059],
         [0.2977, 0.6278, 0.3021],
         [0.0901, 0.8056, 0.1423]],

        [[0.5113, 0.6469, 0.5682],
         [0.7820, 0.0400, 0.7885],
         [0.2431, 0.7600, 0.5513],
         ...,
         [0.1602, 0.2946, 0.0853],
         [0.3207, 0.2084, 0.6262],
         [0.7627, 0.4998, 0.5319]],

        [[0.1616, 0.1272, 0.2456],
         [0.7266, 0.1104, 0.4954],
         [0.1908, 0.0184, 0.3609],
         ...,
         [0.4104, 0.4030, 0.8169],
         [0.1570, 0.9246, 0.4069],
         [0.7973, 0.5987, 0.9244]],

        ...,

        [[0.5977, 0.4172, 0.3977],
         [0.6185, 0.4983, 0.1604],
         [0.3760, 0.8455, 0.8513],
         ...,
         [0.2331, 0.0358, 0.8064],
         [0.6740, 0.4934, 0.8235],
         [0.3921, 0.2649, 0.9592]],

        [[0.1810, 0.5338, 0.3070],
         [0.1870, 0.2737, 0.4759],
         [0.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy



In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
# Get all values of 0 dim but only the 1 index value
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,2,2]

tensor([9])

## PyTorch tensors & NumPy

NumPy is popular scientific Python numerical computing library

And beacause of this, PyTorch has funcationality to interact with it.

* Data in MumPy, want inPyTorch tensor -> `torch.from_numpy `(ndArray)`
* PyTorch tensor -> NumPy -> `torch.NumPy.Tensor`

In [ ]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to `tensor`
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random number -> tensor operations -> update random number to try and make them of the data -> again -> again -> again`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the radomness

In [ ]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.1732, 0.9325, 0.8601, 0.4983],
        [0.8683, 0.2646, 0.0968, 0.4523],
        [0.6608, 0.6178, 0.4869, 0.4536]])
tensor([[0.2648, 0.6044, 0.0273, 0.1912],
        [0.9613, 0.6331, 0.1497, 0.3488],
        [0.1206, 0.5234, 0.6156, 0.1161]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensors

import torch
# Set the radnom seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tnsor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tnsor_D)
print(random_tensor_C == random_tnsor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPU = fater computation on number , thanks to CUDA + NVIDIA hardware + PYTorch wokring behind the scenes

## 1. Getting a GPU


In [2]:
!nvidia-smi

Sun Jul 12 23:40:39 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices

In [6]:
torch.cuda.device_count()

1

## 3. Putting tensors ( and Models) on the GPU
The reason we want our tensors/models on the GPU is becasue using a GPU results faster computation

In [7]:
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Excercise & Extra-Curriculam

In [10]:
import torch

In [13]:
X=torch.rand(size=(7,7))
X,X.shape

(tensor([[0.9529, 0.5240, 0.2393, 0.8193, 0.2144, 0.3825, 0.4028],
         [0.3134, 0.4843, 0.2452, 0.4506, 0.0584, 0.1380, 0.3711],
         [0.1536, 0.1360, 0.3338, 0.7894, 0.5951, 0.3591, 0.7178],
         [0.9117, 0.7564, 0.3165, 0.7810, 0.4142, 0.4265, 0.3244],
         [0.2517, 0.2672, 0.2126, 0.8932, 0.1456, 0.8785, 0.4464],
         [0.1544, 0.8893, 0.0553, 0.3841, 0.3954, 0.7126, 0.9507],
         [0.3022, 0.4089, 0.7923, 0.2356, 0.5091, 0.7755, 0.2910]]),
 torch.Size([7, 7]))